name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

         # Step 3: Log in to Docker Hub (if pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: docker buildx build -t estheronyinye/my_app .

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Load the Docker image
      - name: Load the Docker image
        run: docker buildx build -t estheronyinye/my_app --load .

      # Step 3: Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker buildx build -t estheronyinye/my_app --push .

      # Step 4: Test the Docker image
      - name: Run automated tests
        run: |
          docker run -d -p 80:80 --name my_app-test estheronyinye/my_app .
          sleep 10
          curl http://localhost:80
          docker stop my_app-test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # Step 2: Pull the Docker image from Dockerhub
      - name: Pull the Docker image
        run: docker pull estheronyinye/my_app

      # Step 3: Deploy to staging (with Docker container)
      - name: Deploy to staging
        run: |
            docker stop my_app-staging || true
            docker rm my_app-staging || true
            docker run -d -p 80:80 --name my_app-staging estheronyinye/my_app . 
