name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub (if pushing to Docker Hub)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      # Step 4: Build the Docker image
      - name: Build the Docker image
        run: docker build -t my_app:{{ github.sha }}

       # Step 5: Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push my_app:${{ github.sha }}

  # Step 6: Deploy to staging (with Docker container)
      - name: Deploy to staging
        run: |
          docker run -d -p 80:80 --name my_app-staging my_app:${{ github.sha }}
            
